/*   Messages related to the MENU library.
/*
msg err1
  lan english -def
    Menu entry name previously set to "%p1s" on attempt to set name to "%p2s".
msg err2
  lan english -def
    Menu entry "%p1s" already added to menu on attempt to change sort sequence.
msg err3
  lan english -def
    Menu entry "%p1s" already added to menu on new attempt to add to menu.
msg err4
  lan english -def
    Menu entry action already set to new attempt to set the action.
msg err5
  lan english -def
    Name not set on attempt to add menu entry to its menu.
msg err6
  lan english -def
    Action for menu entry "%p1s" not set on attempt to add entry to menu.
msg err7
  lan english -def
    No file name associated with menu tree on attempt to write tree to file.
